name: CI

on: [push]

jobs:
  eslint:
    name: Lint code base check
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm ci

      - name: Runs eslint
        run: npm run lint
